apiVersion: v1
kind: Service
metadata:
  labels:
    app: static-html-image
  name: static-html-image-service
  namespace: default
spec:
  ports:
  - nodePort: 32286
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static-html-image
  type: LoadBalancer
