apiVersion: v1
kind: Service
metadata:
  labels:
    app: static-html-image
  name: static-html-image-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: static-html-image
  type: LoadBalancer
